version: '1.0.{build}'
image: Visual Studio 2019 Preview
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Swashbuckle.AspNetCore.Filters/Swashbuckle.AspNetCore.Filters.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./src/Swashbuckle.AspNetCore.Filters/Swashbuckle.AspNetCore.Filters.csproj -f netstandard2.0
after_build:
  # For once the build has completed
artifacts:
 # - path: '\src\bin\Debug\netcoreapp1.1\publish'
 #  name: WebSite
 #  type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./test/Swashbuckle.AspNetCore.Filters.Test/Swashbuckle.AspNetCore.Filters.Test.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd ./test/Swashbuckle.AspNetCore.Filters.Test
  - cmd: dotnet test
  - cmd: cd ../..
  # restore packages for our unit tests
  - cmd: dotnet restore ./test/Swashbuckle.AspNetCore.Filters.Test6/Swashbuckle.AspNetCore.Filters.Test6.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd ./test/Swashbuckle.AspNetCore.Filters.Test6
  - cmd: dotnet test
  - cmd: cd ../..
  # restore packages for our unit tests
  - cmd: dotnet restore ./test/Swashbuckle.AspNetCore.Filters.Test3.1/Swashbuckle.AspNetCore.Filters.Test3.1.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd ./test/Swashbuckle.AspNetCore.Filters.Test3.1
  - cmd: dotnet test
  - cmd: cd ../..
  # restore packages for our unit tests
  - cmd: dotnet restore ./test/Swashbuckle.AspNetCore.Filters.Test2.1/Swashbuckle.AspNetCore.Filters.Test2.1.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd ./test/Swashbuckle.AspNetCore.Filters.Test2.1
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy: off